### ISSUE TITLE
break a poem to two when poem is located in the middle of a category (moving all corresponding meta for all poems involved)

### ISSUE THREAD

**Issue by hrmoh** [ganjoor/GanjoorService#293]
- [x] - make sure the existing method checks for its constraints
- [x] - break the poem
- [x] - move all metadata for all poems involved
- [x] - make sure museum links and relations are correct
